# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/jedwards/projects/live-surface/CMakeLists.txt\
/Users/jedwards/projects/live-surface/xcode/CMakeFiles/2.8.10.2/CMakeCCompiler.cmake\
/Users/jedwards/projects/live-surface/xcode/CMakeFiles/2.8.10.2/CMakeCXXCompiler.cmake\
/Users/jedwards/projects/live-surface/xcode/CMakeFiles/2.8.10.2/CMakeSystem.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCInformation.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCXXInformation.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCommonLanguageInclude.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeGenericSystem.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeParseArguments.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/Clang-C.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/Clang-CXX.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/Clang.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/GNU.cmake\
/opt/local/share/cmake-2.8/Modules/FindGLUT.cmake\
/opt/local/share/cmake-2.8/Modules/FindJPEG.cmake\
/opt/local/share/cmake-2.8/Modules/FindOpenGL.cmake\
/opt/local/share/cmake-2.8/Modules/FindPNG.cmake\
/opt/local/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake\
/opt/local/share/cmake-2.8/Modules/FindPackageMessage.cmake\
/opt/local/share/cmake-2.8/Modules/FindZLIB.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-Clang-C.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-Clang-CXX.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-Clang.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/UnixPaths.cmake
	/opt/local/bin/cmake -H/Users/jedwards/projects/live-surface -B/Users/jedwards/projects/live-surface/xcode
